# This is a k8s deployment file
kind: Deployment
apiVersion: apps/v1
metadata:
  name: agora-chat-localbackend
  labels:
    app: agora-chat-localbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agora-chat-localbackend
  template:
    metadata:
      labels:
        app: agora-chat-localbackend
    spec:
      containers:
      - name: agora-chat-localbackend
        image: erabliereapi/product-api:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "0.25"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        ports:
        - containerPort: 3000
          protocol: TCP
