apiSettings:
  serviceUrl: http://localhost:3000
  bodySizeLimit: 25mb
  mode: memory # memory, camunda or relay
  prefix: /
  relayUrl: http://localhost:3010

camunda:
  url: http://localhost:32002/engine-rest
  processKey: Product_Process

chaos:
  percentageError: 0.00
  percentageDelay: 0.00
  randomDelaiMin: 0
  randomDelaiMax: 2500

logger:
  library: winston
  level: verbose
  title: 'ProductAPI'
  environment: 'development'
  enableFileLogging: false

agora:
  appId: 'your-app-id'
  appCertificate: 'your-app-certificate'