apiSettings:
  bodySizeLimit: 25mb
  mode: memory
  prefix: /

camunda:
  url: http://192.168.1.2:32002/engine-rest
  processKey: Process_06ij0ns

chaos:
  percentageError: 0.00
  percentageDelay: 0.00
  randomDelaiMin: 0
  randomDelaiMax: 2500

logger:
  library: winston
  level: verbose
  title: 'ProductAPI'
  environment: 'development'
  enableFileLogging: false