name: LearnNestJS-Docker-CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - '*.yaml'
      - '*.md'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - .github/**
      - '*.yaml'
      - '*.md'
  workflow_dispatch:

env:
  REGISTRY_HOSTNAME: erabliereapi
  IMAGE_NAME: product-api
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login into dockerhub when not running in pull request
      - name: Login to Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.registryUsername }}
          password: ${{ secrets.registryPassword }}

      # Build the image
      - name: Docker build
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # Tag the images
      - name: Docker tag
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker tag $IMAGE_NAME:$IMAGE_TAG $REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG

      # Push the image
      - name: Docker push
        if: ${{ github.ref == 'refs/heads/main' }}
        run: docker push $REGISTRY_HOSTNAME/$IMAGE_NAME:$IMAGE_TAG